-- Insert Data samples
INSERT INTO CFG_BP_PARAMS (ID, NAME) VALUES ( 0, "Default" );
INSERT INTO CFG_BP_PARAMS (ID, NAME) VALUES ( 1, "Customer Number" );
INSERT INTO CFG_BP_PARAMS (ID, NAME) VALUES ( 2, "Product" );
INSERT INTO CFG_BP_PARAMS (ID, NAME) VALUES ( 3, "Investment" );
INSERT INTO CFG_BP_PARAMS (ID, NAME) VALUES ( 4, "Deposit" );
INSERT INTO CFG_BP_PARAMS (ID, NAME) VALUES ( 5, "Reason Text" );

INSERT INTO CFG_BP_STAGES (ID, CODE, NAME) VALUES ( 1, "1", "Default" );
INSERT INTO CFG_BP_STAGES (ID, CODE, NAME) VALUES ( 2, "2", "Action" );
INSERT INTO CFG_BP_STAGES (ID, CODE, NAME) VALUES ( 3, "4", "Decision (Process)" );
INSERT INTO CFG_BP_STAGES (ID, CODE, NAME) VALUES ( 4, "65536", "Decision (VBO)" );
INSERT INTO CFG_BP_STAGES (ID, CODE, NAME) VALUES ( 5, "8", "Calculation" );
INSERT INTO CFG_BP_STAGES (ID, CODE, NAME) VALUES ( 6, "536870912", "Multi-Calculation" );
INSERT INTO CFG_BP_STAGES (ID, CODE, NAME) VALUES ( 7, "128", "Page" );
INSERT INTO CFG_BP_STAGES (ID, CODE, NAME) VALUES ( 8, "1024", "Start (Process)" );
INSERT INTO CFG_BP_STAGES (ID, CODE, NAME) VALUES ( 9, "262144", "Start (VBO)" );
INSERT INTO CFG_BP_STAGES (ID, CODE, NAME) VALUES ( 10, "2048", "End (Process)" );
INSERT INTO CFG_BP_STAGES (ID, CODE, NAME) VALUES ( 11, "131072", "writer" );
INSERT INTO CFG_BP_STAGES (ID, CODE, NAME) VALUES ( 12, "262144", "Navigate" );
INSERT INTO CFG_BP_STAGES (ID, CODE, NAME) VALUES ( 13, "4194304", "Wait" );
INSERT INTO CFG_BP_STAGES (ID, CODE, NAME) VALUES ( 14, "16777216", "Alert" );
INSERT INTO CFG_BP_STAGES (ID, CODE, NAME) VALUES ( 15, "33554432", "Exception" );

INSERT INTO CFG_ODBC_CONNECTION ( ID, CONNECTION_STRING, QUERY) 
VALUES ( 1, "DRIVER={ODBC Driver 18 for SQL Server};SERVER=localhost\SQLEXPRESS;DATABASE=blueprism;UID=sa;PWD=sa123@;ENCRYPT=No", 
"SELECT logid, LOG.sessionnumber, stagename, pagename, result,LOG.startdatetime, actionname, stagetype, attributexml,
IIF(processname IS NULL, 'VBO', 'PROC') as OBJECT_TYPE, 
IIF(processname IS NULL, objectname, processname) as OBJECT_NAME,
BPAResource.name as DWName
FROM $tablelog AS LOG, BPASession, BPAResource
WHERE LOG.sessionnumber IN 
(SELECT distinct sessionnumber  
            FROM $tablelog 
		    WHERE processname = '$processname'
            AND $delta)
AND LOG.sessionnumber = BPASession.sessionnumber
AND BPAResource.resourceid = BPASession.runningresourceid
AND stagetype NOT IN($stagetypefilters)
AND $onlybpprocess" );

INSERT INTO CFG_BP_REPO ( ID, PROCESS_NAME, INCLUDE_VBO, UNICODE_SUPPORT, START_END_FILTER, DELTA_LOAD, DELTA_TAG_FILE, FK_ODBC_ID) 
VALUES ( 1, "IFA Application Process", 1, 0, 1, 1, "delta.tag", 1 );

INSERT INTO CFG_BP_STAGE_FILTERS ( FK_BPSTAGE_ID, FK_BPREPO_ID) VALUES ( 1, 1 );
INSERT INTO CFG_BP_STAGE_FILTERS ( FK_BPSTAGE_ID, FK_BPREPO_ID) VALUES ( 3, 1 );
INSERT INTO CFG_BP_STAGE_FILTERS ( FK_BPSTAGE_ID, FK_BPREPO_ID) VALUES ( 4, 1 );
INSERT INTO CFG_BP_STAGE_FILTERS ( FK_BPSTAGE_ID, FK_BPREPO_ID) VALUES ( 5, 1 );
INSERT INTO CFG_BP_STAGE_FILTERS ( FK_BPSTAGE_ID, FK_BPREPO_ID) VALUES ( 6, 1 );

INSERT INTO CFG_BP_PARAMS_COLLECT (FK_PARAMS_ID, FK_BPREPO_ID) VALUES ( 1, 1 );
INSERT INTO CFG_BP_PARAMS_COLLECT (FK_PARAMS_ID, FK_BPREPO_ID) VALUES ( 2, 1 );
INSERT INTO CFG_BP_PARAMS_COLLECT (FK_PARAMS_ID, FK_BPREPO_ID) VALUES ( 3, 1 );
INSERT INTO CFG_BP_PARAMS_COLLECT (FK_PARAMS_ID, FK_BPREPO_ID) VALUES ( 4, 1 );
INSERT INTO CFG_BP_PARAMS_COLLECT (FK_PARAMS_ID, FK_BPREPO_ID) VALUES ( 5, 1 );

INSERT INTO CFG_BPPISERVER (ID, NAME, DESCRIPTION, TOKEN) 
VALUES (1, "Staging Server", 
"cmVwb3NpdG9yeTpTZVp6czkyVnNsNmtsOTluRy1IZTNCTHNReHl1OEQ5Wkw4Yy1FTjJqZW16VkxhNGpyZkRUTVZGZklYV3JkNDIyQVlxMGV6OENkMThERnZXb01MZHR4dw==", 
"https://bp-staging.timelinepi.com");

INSERT INTO CFG_OTHER ( ID, LOG_FOLDER, LOG_FILENAME, LOG_LEVEL, LOG_FORMAT) 
VALUES ( 1, "C:\Users\BenoitCayla\OneDrive - SS&C Technologies, Inc\03 - BPPI\Demo\BP Logs\IFA (No Bulk)\", 
        "bppi-bridge.log", "DEBUG", "%%(asctime)s|%%(name)s|%%(levelname)s|%%(message)s" );

INSERT INTO CFG_BPPI_REPO_TABLE (ID, NAME, DESCRIPTION) VALUES (1, "New_Table", "New Table");
INSERT INTO CFG_BPPI_REPO_TABLE (ID, NAME, DESCRIPTION) VALUES (2, "bridge_csv", "CSV File");
INSERT INTO CFG_BPPI_REPO_TABLE (ID, NAME, DESCRIPTION) VALUES (3, "bridge_bp_repo", "Blue Prism Repository");

INSERT INTO CFG_BPPI_REPO_TODO (ID, NAME, DESCRIPTION) VALUES (1, "No ToDo", "No ToDo");
INSERT INTO CFG_BPPI_REPO_TODO (ID, NAME, DESCRIPTION) VALUES (2, "todo_bridge_bp_repo", "");

INSERT INTO CFG_EVENTMAP_TABLETYPE ( ID, TABLE_TYPE) VALUES ( 1, "CSV File" );
INSERT INTO CFG_EVENTMAP_TABLETYPE ( ID, TABLE_TYPE) VALUES ( 2, "Database Table" );

INSERT INTO CFG_EVENTMAP (ID, EVENTMAP_TYPE_ID, MAP_TABLE, MAP_COLUMN) VALUES ( 1, 1, "./test/csvevtmap.csv", "concept:name" );
INSERT INTO CFG_EVENTMAP (ID, EVENTMAP_TYPE_ID, MAP_TABLE, MAP_COLUMN) VALUES ( 2, 1, "./test/csvevtmap.csv", NULL );

INSERT INTO CFG_SOURCETYPE (ID, NAME) VALUES ( 1, "csv" );
INSERT INTO CFG_SOURCETYPE (ID, NAME) VALUES ( 2, "xes" );
INSERT INTO CFG_SOURCETYPE (ID, NAME) VALUES ( 3, "excel" );
INSERT INTO CFG_SOURCETYPE (ID, NAME) VALUES ( 4, "bprepo" );
INSERT INTO CFG_SOURCETYPE (ID, NAME) VALUES ( 5, "bpapi" );
INSERT INTO CFG_SOURCETYPE (ID, NAME) VALUES ( 6, "odbc" );
INSERT INTO CFG_SOURCETYPE (ID, NAME) VALUES ( 7, "saptable" );
INSERT INTO CFG_SOURCETYPE (ID, NAME) VALUES ( 8, "chfile" );

INSERT INTO CFG_PIPELINE
	( ID, NAME, DESCRIPTION, 
      FK_SERVER_ID, FK_REPO_TABLE_ID, FK_REPO_TODO_ID, 
      FK_OTHER_ID, FK_EVENTMAP_ID, FK_BPREPO_ID, 
      FK_BPAPI_ID, FK_FILE_ID, FK_SAP_ID, SOURCE_TYPE_ID) 
    VALUES ( 1, "BP Repo IFA", "BP Repo IFA", 
             1, 3, 2, 
             1, NULL, 1, 
             NULL, NULL, NULL, 4);